---
# vars file for yum

packages_list:
  - rsync
  - iproute
  - lsof
  - sudo
  - less
  - net-tools
  - libselinux-python
  - binutils
  - compat-libcap1
  - gcc.x86_64
  - gcc-c++.x86_64
  - glibc.x86_64
  - glibc-devel.x86_64
  - libaio.x86_64
  - libaio-devel.x86_64
  - libgcc.x86_64
  - libstdc++.x86_64
  - libstdc++-devel.x86_64
  - ksh
  - make
  - sysstat
  - sshpass
  - unzip
