---
# vars file for config

soft_no_file: 4096
hard_no_file: 65536
soft_nproc: 2047
hard_nproc: 16384

kernel_params:
    kernel.shmmax: 2147483648
    kernel.shmall: 524288
    net.core.rmem_max: 16777216
    net.core.wmem_max: 16777216
    net.ipv4.tcp_rmem: 4096 87380 16777216
    net.ipv4.tcp_wmem: 4096 65536 16777216
    vm.swappiness: 10
    vm.dirty_background_ratio: 5
    vm.dirty_ratio: 10
    fs.file-max: 262144
    net.ipv4.tcp_keepalive_time: 300
    net.ipv4.tcp_keepalive_intvl: 60
    net.ipv4.tcp_keepalive_probes: 10
    