---

- name: Disable SELinux
  selinux: 
      state: disabled
      
- name: Add oracle security limits
  lineinfile: 
      dest: /etc/security/limits.conf 
      line: "{{ oracle_account.user }} {{ item.limit }} {{ item.type}} {{ item.value }}"
  with_items:
    - { limit: 'soft', type: 'nofile', value: '{{ soft_no_file }}' }
    - { limit: 'hard', type: 'nofile', value: '{{ hard_no_file }}' }
    - { limit: 'soft', type: 'nproc', value: '{{ soft_nproc }}' }
    - { limit: 'hard', type: 'nproc', value: '{{ hard_nproc }}' }

#- name: Add {{ user_mem_args_key }} to use urandom in bashrc
#  lineinfile: 
#      state: present
#      path: "{{ oracle_account.home }}/.bashrc" 
#      regexp: 'export {{ user_mem_args_key }}='
#      line: 'export {{ user_mem_args_key }}="{{ user_mem_args_value }}"'
            
- name: Change kernel parameters
  sysctl: 
      name: "{{ item.key }}"
      value: "{{ item.value }}"
      state: present
  with_dict: "{{ kernel_params }}"
        